############################################## Model Settings ##########################################################
## HuggingFace:
## repo_id: TheBloke/Llama-2-7b-Chat-GGUF
## filename: llama-2-7b-chat.Q4_K_M.gguf

## Template:
## [INST] <<SYS>>
## {system_prompt}
## <</SYS>>
## {prompt}[/INST]


############################################## Prompt Settings #########################################################
mode1:
    model_source:
      repo_id:    'TheBloke/Llama-2-7B-GGUF'
      filename:   'llama-2-7b.Q4_K_M.gguf'

    model_path: ./models/llama-2-7b-chat.Q4_K_M.gguf

    model_kwargs:
      n_threads: 2 # CPU cores
      f16_kv: True
      n_ctx: 2048
      max_tokens: 2048
      temperature: 0.0


    prompt_template:
      input_variables:
        - input
      prefix: |
        [INST] <<SYS>>
        You are a relation-finding assistant, which takes user's text input and extracts relations from it.
        Relation is a type of connection between two objects.
        If one entity somehow relates to another, then we call it a relation.
        Relation is directed, so order matters.
        Output relations in format [Object1, Object2, RelationType] where Object2 has a relation of RelationType with Object1.
        
        Examples:
      suffix:  |
        <</SYS>>
        Prompt: {input}
        
        Relations: [/INST]

      example_separator: "\n\n"
      examples:
        - prompt: |
            Mary, Mike and Alice are friends. Alice is Bob's roommate and Jean hates her.
          relations: |
            [["Mary", "Mike", "friend"], ["Mary", "Alice", "friend"], ["Alice", "Mike", "friend"], ["Alice", "Bob", "roommate"], ["Jean", "Alice", "hate"]]
        - prompt: |
            Washington is the capital city of the United States. The city is located on the east bank of
            the Potomac River, which forms its southwestern border with Virginia and borders Maryland
            to its north and east.
          relations: |
            [["United States", "Washington", "capital"], ["Washington", "Potomac River bank", "location"], ["Washington", "Virginia", "border"], ["Washington", "Maryland", "border"]]



    # Example templating (similar to the main template suffix)
    prompt_template_example:
      input_variables:
        - prompt
        - relations
      template: |
        Prompt: {prompt}
        Relations: {relations}



############################################## Named Prompts ###########################################################
prompt1: |
  The United States of America (U.S.A. or USA), commonly known as the United States (U.S. or US) or America,
  is a country primarily located in North America and consisting of 50 states, a federal district, five major
  unincorporated territories, nine Minor Outlying Islands,[i] and 326 Indian reservations. It is the world's
  third-largest country by both land and total area.[c] It shares land borders with Canada to its north and with Mexico 
  to its south and has maritime borders with the Bahamas, Cuba, Russia, and other nations.[j] With a population of over
  333 million,[k] it is the most populous country in the Americas and the third-most populous in the world. The national
  capital of the United States is Washington, D.C., and its most populous city and principal financial center is 
  New York City.

