name: Daily Python Script

on:
  workflow_dispatch:
    inputs:


  push:
     branches:
     - run


  schedule:
    #- cron:  '0 0 * * 0'      #### 60mins
    - cron:  '0 10 * * *'  ##10:00 UTC everyday
    #   - cron:  '* * */2 * *'

concurrency:
  group: ${{ github.ref }}_long
  cancel-in-progress: true



jobs:
  run_script:
    name: Run Python Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.*  # Replace with your desired Python version

      - name: Install dependencies
        run: |
              pip install fire pandas utilmy praw


      - name: Run Python script with secrets
        env:
          reddit_client_id: ${{ secrets.REDDIT_CLIENT_ID }} 
          reddit_client_secret: ${{ secrets.REDDIT_CLIENT_SECRET }} 
          user_agent: ${{ secrets.USER_AGENT }}
        run: |
              python src/cli_reddittnews.py --query 'machine learning conference,ICML,NeurIPS,OpenAI  --dirout "arita37/ascraper/out"    --verbose 1



      - name: Self push commit
        #vcontinue-on-error: true
        run:  |
          git add -A || echo 'nothing'
          git commit -am "daily" ||   echo 'nothing'
          git push origin run  ||  echo 'nothing2'

          echo 'All finished'
          git branch -a


